services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fast1
    networks:
      - backend-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fast1:
    image: fast1
    container_name: fast1_app
    restart: always
    expose:
      - "8000"
    volumes:
      - ./backend/env.py:/code/env.py:Z
    networks:
      - backend-network

  worker:
    image: fast1
    container_name: fast1_worker
    restart: always
    command: arq worker.WorkerSettings
    volumes:
      - ./backend/env.py:/code/env.py:Z
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
