from ssl import ALERT_DESCRIPTION_DECOMPRESSION_FAILURE

SECRET_KEY = "your‑very‑long‑random‑string"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30


ADMIN_USERNAME = "admin"
ADMIN_EMAIL = "pxperrine@gmail.com"
ADMIN_PASSWORD = "aoeu"
